services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: campaign-chat-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    networks:
      - campaign-chat-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: campaign-chat-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - campaign-chat-network
    restart: unless-stopped

networks:
  campaign-chat-network:
    driver: bridge